console.log("Linked");
var student1 = "Adam";
var student2 = "Marquice";
var student3 = "DeJuan";
var num1 = 10;
var num2 = 5;
var name1 = "Anthony";
var name2 = "Michael";
var name3 = "David";
var name4 = "Jorge";
var name5 = "Jared";
var name6 = "John";
var name7 = "Jacob";
var name8 = "Jinker";
var name9 = "Jason";
var name10 = "Joseph";
var name11 = "Jack";
var name12 = "Julian";
var name13 = "Juan";
var name14 = "Jaxon";
var name15 = "Jeffery";
var name16 = "Joaquin";
var name17 = "Justin";
var name18 = "James";
var name19 = "Johnathan";
var name20 = "Jose";

document.write(`<p> ${student1} </p>`);
document.write(`<p> ${student2} </p>`);
document.write(`<p> ${student3} </p>`);
var sum = num1 + num2;
document.write(`<p> ${sum} </p>`);

document.write(`<p> ${name1} </p>`);
document.write(`<p> ${name2} </p>`);
document.write(`<p> ${name3} </p>`);
document.write(`<p> ${name4} </p>`);
document.write(`<p> ${name5} </p>`);
document.write(`<p> ${name6} </p>`);
document.write(`<p> ${name7} </p>`);
document.write(`<p> ${name8} </p>`);
document.write(`<p> ${name9} </p>`);
document.write(`<p> ${name10} </p>`);
document.write(`<p> ${name11} </p>`);
document.write(`<p> ${name12} </p>`);
document.write(`<p> ${name13} </p>`);
document.write(`<p> ${name14} </p>`);
document.write(`<p> ${name15} </p>`);
document.write(`<p> ${name16} </p>`);
document.write(`<p> ${name17} </p>`);
document.write(`<p> ${name18} </p>`);
document.write(`<p> ${name19} </p>`);
document.write(`<p> ${name20} </p>`);
